### ISSUE TITLE
Cannot create Initiative

### ISSUE THREAD

**Issue by othreed** [dvn0/docker-liquidfeedback-server#1]
Hi,
your docker install works like a charm. But when I access the frontend, I cannot create any initiatives.
How do I enable this?
thanks :)

![screen shot 2018-05-21 at 11 47 31](https://user-images.githubusercontent.com/87859/40301689-2606aacc-5ced-11e8-8113-9a1103239134.png)

**Comment by dvn0** [comment]
I'm working on fixing several things about this setup -- will push commits in the coming week.

**Comment by othreed** [comment]
Hi,
do you have any updates?

**Comment by dvn0** [comment]
Hey, unfortunately we ran into some undocumented SQL issues back in July, and haven't found the time to get back to it and debug. It's on my list though... I'll be sure to follow up here once it happens.

**Comment by dvn0** [comment]
@othreed Looks like we got this working. As for your specific trouble with creating an initiative: That could have just been because the UI makes it much harder to find that it should. You can only create initiatives in side of groups, also, so you must make sure you have at least 1 group.

**Comment by dvn0** [comment]
I'm going to close this, since creating initiatives does seem to work now.
